delete from t_permissions where role_id = 'role101'
delete from t_permissions where role_id = 'role102'
delete from t_role where id = 'role101'
delete from t_role where id = 'role102'
delete from T_USER where id = 'user001'
